---
#VARIABLES

elasticSearch_repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
kibana_repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
logstash_repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"

elasticSearch_ubuntu: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
kibana_ubuntu: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
logstash_ubuntu: "https://packages.elasticsearch.org/GPG-KEY-elasticsearch"

elasticSearch_centos: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
kibana_centos: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
logstash_centos: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"

grafana_repo: "deb https://packages.grafana.com/oss/deb stable main"

grafana_ubuntu: "https://packages.grafana.com/gpg.key"
