---
- hosts: ElasticStack
  become: true

  vars_files:
    - /home/kazuki/CPE_MIDEXAM_OGATA/config.yaml

  roles:
    - ElasticStack

- hosts: nagios
  become: true
  roles:
    - nagios

- hosts: GPI
  become: true

  vars_files:
    - /home/kazuki/CPE_MIDEXAM_OGATA/config.yaml

  roles:
    - GPI

- hosts: LampStack
  become: true
  roles:
    - LampStack

